name: CI Pipeline

on:
  push:

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ github.repository_owner }}
  IMAGE_REPO: ${{ github.event.repository.name }}

jobs:
  # 1) BUILD: instalar deps y (opcional) build
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Build (if defined)
        run: npm run build || echo "No build step"

  # 2) TEST: correr unit tests
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install deps
        run: npm ci
      - name: Run tests
        env:
          NODE_ENV: test
        run: npm test

  # 3) VULNERABILITY SCAN: npm audit
  vulnerability:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Audit dependencies and save report
        run: |
          npm ci
          npm audit --audit-level=moderate --json > audit-report.json || true
      - uses: actions/upload-artifact@v4
        with:
          name: audit-report
          path: audit-report.json

  # 4) SONAR ANALYSIS: SonarCloud
  sonar-analysis:
    needs: vulnerability
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install deps 
        run: npm ci
      - name: Run tests with coverage
        env:
          NODE_ENV: test
        run: npm test
      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npx sonar-scanner \
            -Dsonar.organization=${{ secrets.SONAR_ORG }} \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.sources=. \
            -Dsonar.tests=. \
            -Dsonar.test.inclusions="**/*.test.js" \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info


  # 5) BUILD & PUSH: image tagged con SHA corta y 'latest'
  publish:
    needs: sonar-analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker --quiet

      - name: Determine image tag
        id: tag
        run: echo "sha=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
      - name: Build & push
        run: |
          REPO_LOWER=$(echo "${{ env.IMAGE_REPO }}" | tr '[:upper:]' '[:lower:]')
          IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/$REPO_LOWER
          docker build -t $IMAGE:${{ steps.tag.outputs.sha }} -t $IMAGE:latest .
          docker push $IMAGE:${{ steps.tag.outputs.sha }}
          docker push $IMAGE:latest
          GCR_IMAGE=gcr.io/${{ secrets.GCP_PROJECT }}/$REPO_LOWER
          docker tag $IMAGE:${{ steps.tag.outputs.sha }} $GCR_IMAGE:${{ steps.tag.outputs.sha }}
          docker tag $IMAGE:latest             $GCR_IMAGE:latest
          gcloud auth configure-docker --quiet
          docker push $GCR_IMAGE:${{ steps.tag.outputs.sha }}
          docker push $GCR_IMAGE:latest

  # 6) Terraform
  tf-init:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Authenticate GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Terraform Init
        run: terraform -chdir=terraform init

  tf-plan:
    needs: tf-init
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Terraform Plan
        run: |
          terraform -chdir=terraform plan \
            -var="project=${{ secrets.GCP_PROJECT }}" \
            -var="region=${{ secrets.GCP_REGION }}" \
            -var="credentials=${{ secrets.GCP_CREDENTIALS }}" \
            -out=tfplan

  tf-apply:
    if: github.ref_name == 'main'
    needs: tf-plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve tfplan

  # 7) DEPLOY K8S (sólo en main)
  deploy-gke:
    needs: tf-apply 
    if: github.ref_name == 'main' 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials devops-cluster \
            --region ${{ secrets.GCP_REGION }} \
            --project ${{ secrets.GCP_PROJECT }}

      - name: Deploy manifests to GKE
        run: |
          kubectl apply -f k8s/configmap.yaml
          kubectl apply -f k8s/secret.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/ingress.yaml
          kubectl rollout restart deployment/devops-service
          kubectl rollout status deployment/devops-service --timeout=120s